### ISSUE TITLE
Fix Cors Errors

### ISSUE THREAD

**Issue by jll38** [jll38/njithacks-njitbytes#27]
```Access to XMLHttpRequest at 'https://njitbytes.co/api/breakfast' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

Probably something on the backend to fix

Temporary solution is a proxy server we're sending requests to.

**Comment by vladimir-io** [comment]
Working on this now.

**Comment by Vladimir-G4** [comment]
@jll38 please test to confirm that this issue is fixed
