### ISSUE TITLE
Allow users to favorite certain menu items, will be notified when it's on the menu

### ISSUE THREAD

**Issue by jll38** [jll38/njithacks-njitbytes#32]
On the menu page, users will be able to favorite specific menu items, and if they appear on the menu, users will receive a push notification (once that functionality is developed)

**Comment by vladimir-io** [comment]
If you completed this @jll38, then please add yourself as an assignee and close with the comment "Completed." You can attach the specific pull request made by clicking the gear in the development tab to the right of your window.
