### ISSUE TITLE
Have Consistent Positioning of logo and headers

### ISSUE THREAD

**Issue by vladimir-io** [jll38/njithacks-njitbytes#53]
The positioning of the screen is (from a desktop perspective) the same for the settings and contributors screen, but different from the menu and AI recommendations screen. 

- [ ] Have consistency as far as where the logo is placed on each screen and where the main view is.

**Comment by vladimir-io** [comment]
Finished Home Page Responsiveness for both mobile and desktop

**Comment by vladimir-io** [comment]
Finished Settings Page Responsiveness for both mobile and desktop

**Comment by vladimir-io** [comment]
Finished Contributors Page Responsiveness for both mobile and desktop

**Comment by jll38** [comment]
We should consider utilizing a layout.js so that we keep everything consistent

**Comment by vladimir-io** [comment]
> We should consider utilizing a layout.js so that we keep everything consistent

Will look to add this tonight

**Comment by vladimir-io** [comment]
Completed
